name: Compile OpenWRT
on: workflow_dispatch

jobs:
  my-job:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source
        uses: actions/checkout@v2
      - name: Do the job
        run: ./compile_openwrt.sh
        shell: bash
      - name: Show the File
        run: tree /home/runner/openwrt_work/openwrt-sdk-19.07.4-ipq40xx-generic_gcc-7.5.0_musl_eabi.Linux-x86_64/bin/packages/
        shell: bash
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/openwrt_work/openwrt-sdk-19.07.4-ipq40xx-generic_gcc-7.5.0_musl_eabi.Linux-x86_64/bin/packages/arm_cortex-a7_neon-vfpv4/base/* /home/runner/openwrt_work/openwrt-sdk-19.07.4-ipq40xx-generic_gcc-7.5.0_musl_eabi.Linux-x86_64/bin/packages/arm_cortex-a7_neon-vfpv4/packages/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
