name: Compile OpenWRT
on: push

jobs:
  my-job:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source
        uses: actions/checkout@v2
      - name: Do the job
        run: |
          ls -alh
          ./compile_openwrt.sh
