name: Compile OpenWRT
on: workflow_dispatch

jobs:
  my-job:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source
        uses: actions/checkout@v2
      - name: Do the job
        run: ./compile_openwrt.sh
        shell: bash
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/packages/arm_cortex-a7_neon-vfpv4/base/* bin/packages/arm_cortex-a7_neon-vfpv4/packages/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2
