name: Compile OpenWRT
on: workflow_dispatch

jobs:
  my-job:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source
        uses: actions/checkout@v2
      - name: Do the job
        run: ./compile_openwrt.sh
        shell: bash
      - name: Show the File
        run: tree /home/runner/openwrt_work/output
        shell: bash
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/openwrt_work/output/s*
          file: /home/runner/openwrt_work/output/l*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
