name: Make Sunxi Image
on: workflow_dispatch

jobs:
  my-job:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source
        uses: actions/checkout@v2
      - name: Do the job
        run: ./make_sunxi_image.sh
        shell: bash
      - name: Show the File
        run: tree /home/runner/sunxi_image/output
        shell: bash
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/sunxi_image/output/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
